/**
 * ============================================
 * OJABRIDGE AUTHORITY COUNTRY & CURRENCY DATA
 * ============================================
 * Full authoritative dataset for country selection.
 * Nigeria is the only active market. All others are "Coming Soon".
 * 
 * Usage:
 *   import { COUNTRIES } from '@/lib/countries';
 */

// African countries with currencies (primary focus for Nigeria-first launch)
const AFRICAN_COUNTRIES = [
  { code: 'NG', name: 'Nigeria', currencies: [{ code: 'NGN', active: true }] },
  { code: 'GH', name: 'Ghana', currencies: [{ code: 'GHS', comingSoon: true }] },
  { code: 'KE', name: 'Kenya', currencies: [{ code: 'KES', comingSoon: true }] },
  { code: 'ZA', name: 'South Africa', currencies: [{ code: 'ZAR', comingSoon: true }] },
  { code: 'EG', name: 'Egypt', currencies: [{ code: 'EGP', comingSoon: true }] },
  { code: 'ET', name: 'Ethiopia', currencies: [{ code: 'ETB', comingSoon: true }] },
  { code: 'TZ', name: 'Tanzania', currencies: [{ code: 'TZS', comingSoon: true }] },
  { code: 'UG', name: 'Uganda', currencies: [{ code: 'UGX', comingSoon: true }] },
  { code: 'RW', name: 'Rwanda', currencies: [{ code: 'RWF', comingSoon: true }] },
  { code: 'SN', name: 'Senegal', currencies: [{ code: 'XOF', comingSoon: true }] },
  { code: 'CI', name: "Côte d'Ivoire", currencies: [{ code: 'XOF', comingSoon: true }] },
  { code: 'CM', name: 'Cameroon', currencies: [{ code: 'XAF', comingSoon: true }] },
  { code: 'CD', name: 'DR Congo', currencies: [{ code: 'CDF', comingSoon: true }] },
  { code: 'AO', name: 'Angola', currencies: [{ code: 'AOA', comingSoon: true }] },
  { code: 'MZ', name: 'Mozambique', currencies: [{ code: 'MZN', comingSoon: true }] },
  { code: 'ZM', name: 'Zambia', currencies: [{ code: 'ZMW', comingSoon: true }] },
  { code: 'ZW', name: 'Zimbabwe', currencies: [{ code: 'ZWL', comingSoon: true }] },
  { code: 'BW', name: 'Botswana', currencies: [{ code: 'BWP', comingSoon: true }] },
  { code: 'NA', name: 'Namibia', currencies: [{ code: 'NAD', comingSoon: true }] },
  { code: 'MU', name: 'Mauritius', currencies: [{ code: 'MUR', comingSoon: true }] },
  { code: 'MG', name: 'Madagascar', currencies: [{ code: 'MGA', comingSoon: true }] },
  { code: 'ML', name: 'Mali', currencies: [{ code: 'XOF', comingSoon: true }] },
  { code: 'BF', name: 'Burkina Faso', currencies: [{ code: 'XOF', comingSoon: true }] },
  { code: 'NE', name: 'Niger', currencies: [{ code: 'XOF', comingSoon: true }] },
  { code: 'TD', name: 'Chad', currencies: [{ code: 'XAF', comingSoon: true }] },
  { code: 'GA', name: 'Gabon', currencies: [{ code: 'XAF', comingSoon: true }] },
  { code: 'CG', name: 'Republic of Congo', currencies: [{ code: 'XAF', comingSoon: true }] },
  { code: 'TG', name: 'Togo', currencies: [{ code: 'XOF', comingSoon: true }] },
  { code: 'BJ', name: 'Benin', currencies: [{ code: 'XOF', comingSoon: true }] },
  { code: 'GN', name: 'Guinea', currencies: [{ code: 'GNF', comingSoon: true }] },
  { code: 'SL', name: 'Sierra Leone', currencies: [{ code: 'SLL', comingSoon: true }] },
  { code: 'LR', name: 'Liberia', currencies: [{ code: 'LRD', comingSoon: true }] },
  { code: 'GM', name: 'Gambia', currencies: [{ code: 'GMD', comingSoon: true }] },
  { code: 'MR', name: 'Mauritania', currencies: [{ code: 'MRU', comingSoon: true }] },
  { code: 'DZ', name: 'Algeria', currencies: [{ code: 'DZD', comingSoon: true }] },
  { code: 'TN', name: 'Tunisia', currencies: [{ code: 'TND', comingSoon: true }] },
  { code: 'MA', name: 'Morocco', currencies: [{ code: 'MAD', comingSoon: true }] },
  { code: 'LY', name: 'Libya', currencies: [{ code: 'LYD', comingSoon: true }] },
  { code: 'SD', name: 'Sudan', currencies: [{ code: 'SDG', comingSoon: true }] },
  { code: 'SS', name: 'South Sudan', currencies: [{ code: 'SSP', comingSoon: true }] },
  { code: 'ER', name: 'Eritrea', currencies: [{ code: 'ERN', comingSoon: true }] },
  { code: 'DJ', name: 'Djibouti', currencies: [{ code: 'DJF', comingSoon: true }] },
  { code: 'SO', name: 'Somalia', currencies: [{ code: 'SOS', comingSoon: true }] },
  { code: 'CF', name: 'Central African Republic', currencies: [{ code: 'XAF', comingSoon: true }] },
  { code: 'BI', name: 'Burundi', currencies: [{ code: 'BIF', comingSoon: true }] },
  { code: 'MW', name: 'Malawi', currencies: [{ code: 'MWK', comingSoon: true }] },
  { code: 'SZ', name: 'Eswatini', currencies: [{ code: 'SZL', comingSoon: true }] },
  { code: 'LS', name: 'Lesotho', currencies: [{ code: 'LSL', comingSoon: true }] },
  { code: 'SC', name: 'Seychelles', currencies: [{ code: 'SCR', comingSoon: true }] },
  { code: 'CV', name: 'Cape Verde', currencies: [{ code: 'CVE', comingSoon: true }] },
  { code: 'ST', name: 'São Tomé and Príncipe', currencies: [{ code: 'STN', comingSoon: true }] },
  { code: 'GQ', name: 'Equatorial Guinea', currencies: [{ code: 'XAF', comingSoon: true }] },
  { code: 'KM', name: 'Comoros', currencies: [{ code: 'KMF', comingSoon: true }] },
  { code: 'AO', name: 'Angola', currencies: [{ code: 'AOA', comingSoon: true }] },
];

// International countries
const INTERNATIONAL_COUNTRIES = [
  { code: 'US', name: 'United States', currencies: [{ code: 'USD', comingSoon: true }] },
  { code: 'GB', name: 'United Kingdom', currencies: [{ code: 'GBP', comingSoon: true }] },
  { code: 'CA', name: 'Canada', currencies: [{ code: 'CAD', comingSoon: true }] },
  { code: 'DE', name: 'Germany', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'FR', name: 'France', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'IT', name: 'Italy', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'ES', name: 'Spain', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'NL', name: 'Netherlands', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'BE', name: 'Belgium', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'PT', name: 'Portugal', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'CH', name: 'Switzerland', currencies: [{ code: 'CHF', comingSoon: true }] },
  { code: 'AT', name: 'Austria', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'SE', name: 'Sweden', currencies: [{ code: 'SEK', comingSoon: true }] },
  { code: 'NO', name: 'Norway', currencies: [{ code: 'NOK', comingSoon: true }] },
  { code: 'DK', name: 'Denmark', currencies: [{ code: 'DKK', comingSoon: true }] },
  { code: 'FI', name: 'Finland', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'IE', name: 'Ireland', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'PL', name: 'Poland', currencies: [{ code: 'PLN', comingSoon: true }] },
  { code: 'CZ', name: 'Czech Republic', currencies: [{ code: 'CZK', comingSoon: true }] },
  { code: 'HU', name: 'Hungary', currencies: [{ code: 'HUF', comingSoon: true }] },
  { code: 'RO', name: 'Romania', currencies: [{ code: 'RON', comingSoon: true }] },
  { code: 'BG', name: 'Bulgaria', currencies: [{ code: 'BGN', comingSoon: true }] },
  { code: 'HR', name: 'Croatia', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'GR', name: 'Greece', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'TR', name: 'Turkey', currencies: [{ code: 'TRY', comingSoon: true }] },
  { code: 'RU', name: 'Russia', currencies: [{ code: 'RUB', comingSoon: true }] },
  { code: 'UA', name: 'Ukraine', currencies: [{ code: 'UAH', comingSoon: true }] },
  { code: 'AE', name: 'United Arab Emirates', currencies: [{ code: 'AED', comingSoon: true }] },
  { code: 'SA', name: 'Saudi Arabia', currencies: [{ code: 'SAR', comingSoon: true }] },
  { code: 'QA', name: 'Qatar', currencies: [{ code: 'QAR', comingSoon: true }] },
  { code: 'KW', name: 'Kuwait', currencies: [{ code: 'KWD', comingSoon: true }] },
  { code: 'BH', name: 'Bahrain', currencies: [{ code: 'BHD', comingSoon: true }] },
  { code: 'OM', name: 'Oman', currencies: [{ code: 'OMR', comingSoon: true }] },
  { code: 'IL', name: 'Israel', currencies: [{ code: 'ILS', comingSoon: true }] },
  { code: 'JP', name: 'Japan', currencies: [{ code: 'JPY', comingSoon: true }] },
  { code: 'CN', name: 'China', currencies: [{ code: 'CNY', comingSoon: true }] },
  { code: 'KR', name: 'South Korea', currencies: [{ code: 'KRW', comingSoon: true }] },
  { code: 'IN', name: 'India', currencies: [{ code: 'INR', comingSoon: true }] },
  { code: 'PK', name: 'Pakistan', currencies: [{ code: 'PKR', comingSoon: true }] },
  { code: 'BD', name: 'Bangladesh', currencies: [{ code: 'BDT', comingSoon: true }] },
  { code: 'LK', name: 'Sri Lanka', currencies: [{ code: 'LKR', comingSoon: true }] },
  { code: 'TH', name: 'Thailand', currencies: [{ code: 'THB', comingSoon: true }] },
  { code: 'VN', name: 'Vietnam', currencies: [{ code: 'VND', comingSoon: true }] },
  { code: 'PH', name: 'Philippines', currencies: [{ code: 'PHP', comingSoon: true }] },
  { code: 'MY', name: 'Malaysia', currencies: [{ code: 'MYR', comingSoon: true }] },
  { code: 'ID', name: 'Indonesia', currencies: [{ code: 'IDR', comingSoon: true }] },
  { code: 'SG', name: 'Singapore', currencies: [{ code: 'SGD', comingSoon: true }] },
  { code: 'HK', name: 'Hong Kong', currencies: [{ code: 'HKD', comingSoon: true }] },
  { code: 'TW', name: 'Taiwan', currencies: [{ code: 'TWD', comingSoon: true }] },
  { code: 'AU', name: 'Australia', currencies: [{ code: 'AUD', comingSoon: true }] },
  { code: 'NZ', name: 'New Zealand', currencies: [{ code: 'NZD', comingSoon: true }] },
  { code: 'BR', name: 'Brazil', currencies: [{ code: 'BRL', comingSoon: true }] },
  { code: 'MX', name: 'Mexico', currencies: [{ code: 'MXN', comingSoon: true }] },
  { code: 'AR', name: 'Argentina', currencies: [{ code: 'ARS', comingSoon: true }] },
  { code: 'CL', name: 'Chile', currencies: [{ code: 'CLP', comingSoon: true }] },
  { code: 'CO', name: 'Colombia', currencies: [{ code: 'COP', comingSoon: true }] },
  { code: 'PE', name: 'Peru', currencies: [{ code: 'PEN', comingSoon: true }] },
  { code: 'EC', name: 'Ecuador', currencies: [{ code: 'USD', comingSoon: true }] },
  { code: 'UY', name: 'Uruguay', currencies: [{ code: 'UYU', comingSoon: true }] },
  { code: 'PA', name: 'Panama', currencies: [{ code: 'PAB', comingSoon: true }] },
  { code: 'CR', name: 'Costa Rica', currencies: [{ code: 'CRC', comingSoon: true }] },
  { code: 'DO', name: 'Dominican Republic', currencies: [{ code: 'DOP', comingSoon: true }] },
  { code: 'JM', name: 'Jamaica', currencies: [{ code: 'JMD', comingSoon: true }] },
  { code: 'TT', name: 'Trinidad and Tobago', currencies: [{ code: 'TTD', comingSoon: true }] },
  { code: 'BB', name: 'Barbados', currencies: [{ code: 'BBD', comingSoon: true }] },
  { code: 'BS', name: 'Bahamas', currencies: [{ code: 'BSD', comingSoon: true }] },
  { code: 'HT', name: 'Haiti', currencies: [{ code: 'HTG', comingSoon: true }] },
  { code: 'CU', name: 'Cuba', currencies: [{ code: 'CUP', comingSoon: true }] },
  { code: 'GT', name: 'Guatemala', currencies: [{ code: 'GTQ', comingSoon: true }] },
  { code: 'HN', name: 'Honduras', currencies: [{ code: 'HNL', comingSoon: true }] },
  { code: 'SV', name: 'El Salvador', currencies: [{ code: 'USD', comingSoon: true }] },
  { code: 'NI', name: 'Nicaragua', currencies: [{ code: 'NIO', comingSoon: true }] },
  { code: 'PY', name: 'Paraguay', currencies: [{ code: 'PYG', comingSoon: true }] },
  { code: 'BO', name: 'Bolivia', currencies: [{ code: 'BOB', comingSoon: true }] },
  { code: 'VE', name: 'Venezuela', currencies: [{ code: 'VES', comingSoon: true }] },
  { code: 'GY', name: 'Guyana', currencies: [{ code: 'GYD', comingSoon: true }] },
  { code: 'SR', name: 'Suriname', currencies: [{ code: 'SRD', comingSoon: true }] },
  { code: 'FK', name: 'Falkland Islands', currencies: [{ code: 'FKP', comingSoon: true }] },
  { code: 'GF', name: 'French Guiana', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'GP', name: 'Guadeloupe', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'MQ', name: 'Martinique', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'RE', name: 'Réunion', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'YT', name: 'Mayotte', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'NC', name: 'New Caledonia', currencies: [{ code: 'XPF', comingSoon: true }] },
  { code: 'PF', name: 'French Polynesia', currencies: [{ code: 'XPF', comingSoon: true }] },
  { code: 'WF', name: 'Wallis and Futuna', currencies: [{ code: 'XPF', comingSoon: true }] },
  { code: 'SB', name: 'Solomon Islands', currencies: [{ code: 'SBD', comingSoon: true }] },
  { code: 'FJ', name: 'Fiji', currencies: [{ code: 'FJD', comingSoon: true }] },
  { code: 'PG', name: 'Papua New Guinea', currencies: [{ code: 'PGK', comingSoon: true }] },
  { code: 'VU', name: 'Vanuatu', currencies: [{ code: 'VUV', comingSoon: true }] },
  { code: 'WS', name: 'Samoa', currencies: [{ code: 'WST', comingSoon: true }] },
  { code: 'TO', name: 'Tonga', currencies: [{ code: 'TOP', comingSoon: true }] },
  { code: 'KI', name: 'Kiribati', currencies: [{ code: 'AUD', comingSoon: true }] },
  { code: 'MH', name: 'Marshall Islands', currencies: [{ code: 'USD', comingSoon: true }] },
  { code: 'FM', name: 'Micronesia', currencies: [{ code: 'USD', comingSoon: true }] },
  { code: 'PW', name: 'Palau', currencies: [{ code: 'USD', comingSoon: true }] },
  { code: 'NR', name: 'Nauru', currencies: [{ code: 'AUD', comingSoon: true }] },
  { code: 'TV', name: 'Tuvalu', currencies: [{ code: 'AUD', comingSoon: true }] },
  { code: 'IS', name: 'Iceland', currencies: [{ code: 'ISK', comingSoon: true }] },
  { code: 'LU', name: 'Luxembourg', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'MT', name: 'Malta', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'CY', name: 'Cyprus', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'SK', name: 'Slovakia', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'SI', name: 'Slovenia', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'EE', name: 'Estonia', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'LV', name: 'Latvia', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'LT', name: 'Lithuania', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'MD', name: 'Moldova', currencies: [{ code: 'MDL', comingSoon: true }] },
  { code: 'GE', name: 'Georgia', currencies: [{ code: 'GEL', comingSoon: true }] },
  { code: 'AM', name: 'Armenia', currencies: [{ code: 'AMD', comingSoon: true }] },
  { code: 'AZ', name: 'Azerbaijan', currencies: [{ code: 'AZN', comingSoon: true }] },
  { code: 'KZ', name: 'Kazakhstan', currencies: [{ code: 'KZT', comingSoon: true }] },
  { code: 'UZ', name: 'Uzbekistan', currencies: [{ code: 'UZS', comingSoon: true }] },
  { code: 'KG', name: 'Kyrgyzstan', currencies: [{ code: 'KGS', comingSoon: true }] },
  { code: 'TJ', name: 'Tajikistan', currencies: [{ code: 'TJS', comingSoon: true }] },
  { code: 'TM', name: 'Turkmenistan', currencies: [{ code: 'TMT', comingSoon: true }] },
  { code: 'MN', name: 'Mongolia', currencies: [{ code: 'MNT', comingSoon: true }] },
  { code: 'MM', name: 'Myanmar', currencies: [{ code: 'MMK', comingSoon: true }] },
  { code: 'KH', name: 'Cambodia', currencies: [{ code: 'KHR', comingSoon: true }] },
  { code: 'LA', name: 'Laos', currencies: [{ code: 'LAK', comingSoon: true }] },
  { code: 'BN', name: 'Brunei', currencies: [{ code: 'BND', comingSoon: true }] },
  { code: 'TL', name: 'Timor-Leste', currencies: [{ code: 'USD', comingSoon: true }] },
  { code: 'NP', name: 'Nepal', currencies: [{ code: 'NPR', comingSoon: true }] },
  { code: 'BT', name: 'Bhutan', currencies: [{ code: 'BTN', comingSoon: true }] },
  { code: 'MV', name: 'Maldives', currencies: [{ code: 'MVR', comingSoon: true }] },
  { code: 'AF', name: 'Afghanistan', currencies: [{ code: 'AFN', comingSoon: true }] },
  { code: 'IQ', name: 'Iraq', currencies: [{ code: 'IQD', comingSoon: true }] },
  { code: 'IR', name: 'Iran', currencies: [{ code: 'IRR', comingSoon: true }] },
  { code: 'SY', name: 'Syria', currencies: [{ code: 'SYP', comingSoon: true }] },
  { code: 'JO', name: 'Jordan', currencies: [{ code: 'JOD', comingSoon: true }] },
  { code: 'LB', name: 'Lebanon', currencies: [{ code: 'LBP', comingSoon: true }] },
  { code: 'PS', name: 'Palestine', currencies: [{ code: 'ILS', comingSoon: true }] },
  { code: 'YE', name: 'Yemen', currencies: [{ code: 'YER', comingSoon: true }] },
  { code: 'BY', name: 'Belarus', currencies: [{ code: 'BYN', comingSoon: true }] },
  { code: 'BA', name: 'Bosnia and Herzegovina', currencies: [{ code: 'BAM', comingSoon: true }] },
  { code: 'RS', name: 'Serbia', currencies: [{ code: 'RSD', comingSoon: true }] },
  { code: 'ME', name: 'Montenegro', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'MK', name: 'North Macedonia', currencies: [{ code: 'MKD', comingSoon: true }] },
  { code: 'AL', name: 'Albania', currencies: [{ code: 'ALL', comingSoon: true }] },
  { code: 'XK', name: 'Kosovo', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'AD', name: 'Andorra', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'MC', name: 'Monaco', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'LI', name: 'Liechtenstein', currencies: [{ code: 'CHF', comingSoon: true }] },
  { code: 'SM', name: 'San Marino', currencies: [{ code: 'EUR', comingSoon: true }] },
  { code: 'VA', name: 'Vatican City', currencies: [{ code: 'EUR', comingSoon: true }] },
];

// Deduplicate by code (Angola appears twice in African list)
const seen = new Set();
const deduped = [...AFRICAN_COUNTRIES, ...INTERNATIONAL_COUNTRIES].filter(c => {
  if (seen.has(c.code)) return false;
  seen.add(c.code);
  return true;
}).sort((a, b) => a.name.localeCompare(b.name));

// Put Nigeria first
export const COUNTRIES = [
  deduped.find(c => c.code === 'NG'),
  ...deduped.filter(c => c.code !== 'NG'),
];

export const CURRENCY_SYMBOLS = {
  NGN: '₦', USD: '$', GBP: '£', EUR: '€', GHS: 'GH₵', KES: 'KSh', ZAR: 'R',
  EGP: 'E£', ETB: 'Br', TZS: 'TSh', UGX: 'USh', RWF: 'FRw', XOF: 'CFA',
  XAF: 'FCFA', CDF: 'FC', AOA: 'Kz', MZN: 'MT', ZMW: 'ZK', ZWL: '$',
  BWP: 'P', NAD: 'N$', MUR: '₨', MGA: 'Ar', GNF: 'FG', SLL: 'Le',
  LRD: 'L$', GMD: 'D', MRU: 'UM', DZD: 'DA', TND: 'DT', MAD: 'MAD',
  LYD: 'LD', SDG: 'SDG', SSP: 'SSP', ERN: 'Nfk', DJF: 'Fdj', SOS: 'Sh',
  BIF: 'FBu', MWK: 'MK', SZL: 'E', LSL: 'L', SCR: '₨', CVE: '$',
  STN: 'Db', KMF: 'CF', CHF: 'CHF', TRY: '₺', RUB: '₽', UAH: '₴',
  AED: 'د.إ', SAR: '﷼', QAR: 'QR', KWD: 'KD', BHD: 'BD', OMR: '﷼',
  ILS: '₪', JPY: '¥', CNY: '¥', KRW: '₩', INR: '₹', PKR: '₨',
  BDT: '৳', LKR: '₨', THB: '฿', VND: '₫', PHP: '₱', MYR: 'RM',
  IDR: 'Rp', SGD: 'S$', HKD: 'HK$', TWD: 'NT$', AUD: 'A$', NZD: 'NZ$',
  BRL: 'R$', MXN: 'Mex$', ARS: 'AR$', CLP: 'CL$', COP: 'Col$',
  PEN: 'S/', UYU: '$U', PAB: 'B/.', CRC: '₡', DOP: 'RD$', JMD: 'J$',
  TTD: 'TT$', BBD: 'Bds$', BSD: 'B$', HTG: 'G', CUP: '₱', GTQ: 'Q',
  HNL: 'L', NIO: 'C$', PYG: '₲', BOB: 'Bs', VES: 'Bs', GYD: 'G$',
  SRD: 'S$', FKP: 'FK£', SBD: 'SI$', FJD: 'FJ$', PGK: 'K', VUV: 'VT',
  WST: 'WS$', TOP: 'T$', ISK: 'kr', MDL: 'L', GEL: '₾', AMD: '֏',
  AZN: '₼', KZT: '₸', UZS: 'so', KGS: 'сом', TJS: 'SM', TMT: 'm',
  MNT: '₮', MMK: 'K', KHR: '៛', LAK: '₭', BND: 'B$', NPR: 'रू',
  BTN: 'Nu.', MVR: 'Rf', AFN: 'Af', IQD: 'ع.د', IRR: '﷼', SYP: '£S',
  JOD: 'JD', LBP: 'L£', YER: '﷼', BYN: 'Br', BAM: 'KM', RSD: 'din',
  MKD: 'ден', ALL: 'L', CAD: 'C$', PLN: 'zł', CZK: 'Kč', HUF: 'Ft',
  RON: 'lei', BGN: 'лв', SEK: 'kr', NOK: 'kr', DKK: 'kr', EGP: 'E£',
};
